"""Filing the digest as a ticket through IdentityHub's public REST API (the same path any scanner
or CI pipeline uses), authenticated with an API key."""

from dataclasses import dataclass

import httpx

from digest.blog import BlogPost

MAX_SUMMARY_LENGTH = 255  # Jira's limit for an issue title


class IdentityHubError(Exception):
    pass


@dataclass(frozen=True)
class CreatedTicket:
    key: str
    url: str


def create_ticket(
    client: httpx.Client, base_url: str, api_key: str, project_key: str, post: BlogPost, summary: str
) -> CreatedTicket:
    title = f"NHI Blog Digest: {post.title}"
    if len(title) > MAX_SUMMARY_LENGTH:
        title = title[: MAX_SUMMARY_LENGTH - 1] + "…"
    description = (
        f"{summary}\n\n"
        f"Source: {post.url}\n"
        f"Published: {post.published:%Y-%m-%d}\n"
        "Summary generated by Claude for the NHI Blog Digest automation."
    )
    try:
        response = client.post(
            f"{base_url.rstrip('/')}/api/v1/findings",
            headers={"Authorization": f"Bearer {api_key}"},
            json={"project_key": project_key, "summary": title, "description": description},
            timeout=30,
        )
    except httpx.HTTPError as exc:
        raise IdentityHubError(f"Couldn't reach IdentityHub at {base_url}: {exc}") from exc

    if response.status_code != 201:
        try:
            body = response.json()
            detail = body.get("detail", body)
            code = f" ({body['code']})" if "code" in body else ""
        except ValueError:
            detail, code = response.text, ""
        raise IdentityHubError(f"IdentityHub returned {response.status_code}{code}: {detail}")
    created = response.json()
    return CreatedTicket(key=created["key"], url=created["url"])
